name: Deploy Dev
on:
  push:
    branches:
      - main
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Update with your python version

    - name: Serverless Deploy
      uses: dhollerbach/github-action-serverless-with-python-requirements@master
      with:
        args: '--stage dev'
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v2
#       with:
#         node-version: '14.x'
#     - name: Install Serverless Framework
#       run: npm install -g serverless
#     - name: Install Serverless Python Requirements
#       run: npm install serverless-python-requirements
#     - name: Install fs-extra
#       run: npm install fs-extra
#     - name: Install NPM dependencies
#       run: npm install
#     - name: Serverless AWS authentication
#       run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
#     - name: Deploy Lambda functions
#       run: sls deploy --stage dev
