name: psa

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:latest
    steps:
      - name: Serverless
        # You may pin to the exact commit or the version.
        # uses: serverless/github-action@8f96a6db886d4ce30c6063dd9919a8a1a4a6d9cf
        uses: serverless/github-action@v1.53.0
      - run: serverless plugin install -n serverless-python-requirements
      - run: serverless deploy --verbose
